MVC Prac/WebApplication6/Models/Base/BaseEntity.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication6.Models.Base
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

MVC Prac/WebApplication6/Models/Slider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices.JavaScript;
using WebApplication6.Models.Base;

namespace WebApplication6.Models
{
    public class Slider:BaseEntity
    {
        [Required]
        [StringLength(3,MinimumLength = 1, ErrorMessage="Maks 3 minimum 1")]
        public string Discount { get; set; }
        [Required]
        [StringLength(30 , MinimumLength = 3, ErrorMessage ="Maks 30 minimum 3")]
        public string Name { get; set; }
        [Required]
        [StringLength(120,MinimumLength = 5 , ErrorMessage = "Maks 120 minimum 5")]
        public string Description { get;set; }
        public string? ImgUrl { get; set; }
        [NotMapped]
        public IFormFile? File { get; set; }
    }
}

MVC Prac/WebApplication6/Areas/Admin/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WebApplication6.DAL;

namespace WebApplication6.Areas.Admin.Controllers
{
    public class AdminController : BaseController
    {
        AppDbContext _db;

        public AdminController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

MVC Prac/WebApplication6/Areas/Admin/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication6.DAL;

namespace WebApplication6.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]

    public class BaseController : Controller
    {
        
    }
}

MVC Prac/WebApplication6/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication6.DAL;
using WebApplication6.Models;

namespace WebApplication6.Areas.Admin.Controllers
{
    
    public class SliderController : BaseController
    {
        AppDbContext _db;
        public SliderController(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            List<Slider> sliders = await _db.slider.ToListAsync();
            return View(sliders);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Slider slider)
        {
            if (slider == null)
            {
                return NotFound();
            }
            _db.slider.Add(slider);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var sliders = _db.slider.FirstOrDefault(p => p.Id == Id);
            //sliders = _db.slider.Find(Id);
            return View(sliders);
        }

        [HttpPost]
        public IActionResult Update (int? id, Slider slider )
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View(slider);

            }
            var oldSlider = _db.slider.FirstOrDefault(p => p.Id == id);
            if (oldSlider == null)
            {
                return NotFound();
            }
            oldSlider.Id = (int)id;
            oldSlider.Name = slider.Name;
            oldSlider.ImgUrl = slider.ImgUrl;
            oldSlider.Description = slider.Description;
            oldSlider.Discount = slider.Discount;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
           var delId = _db.slider.Find(id);
            if (delId != null)
            {
                _db.slider.Remove(delId);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();

        }
    }
}

MVC Prac/WebApplication6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication6.DAL;
using WebApplication6.Models;
using WebApplication6.ViewModels;

namespace WebApplication6.Controllers
{
    public class HomeController : Controller
    {
        AppDbContext _db;

        public HomeController(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            List<Slider> sliders = await _db.slider.ToListAsync();
            //List<Product> products = await _db.slider.ToListAsync();

            HomeVm vm = new HomeVm()
            {
                Sliders= sliders
            };
            return View(vm);
        }
    }
}

MVC Prac/WebApplication6/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/Admin-assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/Admin-assets/https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Admin-assets/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="~/Admin-assets/index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="~/Admin-assets/index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="~/Admin-assets/#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="~/Admin-assets/buttons.html">Buttons</a>
                        <a class="collapse-item" href="~/Admin-assets/cards.html">Cards</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="~/Admin-assets/#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Utilities</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Utilities:</h6>
                        <a class="collapse-item" href="~/Admin-assets/utilities-color.html">Colors</a>
                        <a class="collapse-item" href="~/Admin-assets/utilities-border.html">Borders</a>
                        <a class="collapse-item" href="~/Admin-assets/utilities-animation.html">Animations</a>
                        <a class="collapse-item" href="~/Admin-assets/utilities-other.html">Other</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="~/Admin-assets/#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
	                    <h6 class="collapse-header">Project:</h6>
	                    <a class="collapse-item" asp-controller="Slider" asp-action="Index">Sliders</a>
                        <a class="collapse-item" asp-controller="Product" asp-action="Index">Products</a>

                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="~/Admin-assets/charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span>
                </a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="~/Admin-assets/tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="~/Admin-assets/img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="~/Admin-assets/https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div>

        </ul>
        <!-- End of Sidebar -->
        @RenderBody()
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website 2021</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="~/Admin-assets/#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="~/Admin-assets/login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Admin-assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/Admin-assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Admin-assets/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Admin-assets/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Admin-assets/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Admin-assets/js/demo/chart-area-demo.js"></script>
    <script src="~/Admin-assets/js/demo/chart-pie-demo.js"></script>

</body>

</html>